import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Movies from '../components/Movies'
import Page from '../components/Page'
import Result from '../components/Result'
import Section from '../components/Section'
import Section2 from '../components/Section2'
import Selling from '../components/Selling'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>amazon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div className='bg-[#FFFFFF80]'>
    <Header />

     
    <Result/>

   <Section/>
   <Movies/>
   <Section2/>
    <Page/>
    <Selling/>
   </div>
    
    </div>
  )
}
